export * from './auth/auth.action-types'

export const FETCH_CONTENT_REQUEST = 'FETCH_CONTENT_REQUEST'
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS'
export const FETCH_CONTENT_FAIL = 'FETCH_CONTENT_FAIL'

export const FETCH_ALL_COMMENTS_REQUEST = 'FETCH_ALL_COMMENTS_REQUEST'
export const FETCH_ALL_COMMENTS_SUCCESS = 'FETCH_ALL_COMMENTS_SUCCESS'
export const FETCH_ALL_COMMENTS_FAIL = 'FETCH_ALL_COMMENTS_FAIL'

export const PUSH_COMMENT_REQUEST = 'PUSH_COMMENT_REQUEST'
export const PUSH_COMMENT_SUCCESS = 'PUSH_COMMENT_SUCCESS'
export const PUSH_COMMENT_FAIL = 'PUSH_COMMENT_FAIL'

export const CLEAR_COMMENT_ERRORS = 'CLEAR_COMMENT_ERRORS'
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS'
